# Generated by Django 6.0.4 on 2026-04-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='فرمت\u200cهای مجاز: jpg, png, gif, webp', upload_to='gallery/%Y/%m/', verbose_name='عکس')),
                ('name', models.CharField(help_text='جلسه کاری با تیم برنامه\u200cنویسی', max_length=200, verbose_name='نام عکس')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'گالری تصاویر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sijal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('bio', models.TextField(verbose_name='بیوگرافی')),
                ('image', models.ImageField(upload_to='sijal/%Y/%m/', verbose_name='عکس')),
            ],
        ),
    ]
