# Generated by Django 6.0.4 on 2026-04-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pishnahadroz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='khl')),
                ('akss', models.ImageField(upload_to='sijal/%Y/%m/', verbose_name='عکس')),
                ('qimat', models.CharField(max_length=30, verbose_name='قیمت روز')),
            ],
        ),
    ]
