# Generated by Django 6.0.4 on 2026-04-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pishnahadroz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pishnahadroz',
            name='name',
            field=models.CharField(max_length=25, verbose_name='نام'),
        ),
    ]
