# Generated by Django 6.0.4 on 2026-04-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pishnahadroz_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pishnahadroz',
            old_name='name',
            new_name='namem',
        ),
        migrations.RenameField(
            model_name='pishnahadroz',
            old_name='qimat',
            new_name='qimatt',
        ),
        migrations.AlterField(
            model_name='pishnahadroz',
            name='akss',
            field=models.ImageField(upload_to='pic-food', verbose_name='عکس'),
        ),
    ]
