# Generated by Django 6.0.4 on 2026-04-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_name_pishnahadroz_namem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pishnahadroz',
            name='akss',
            field=models.ImageField(blank=True, null=True, upload_to='pic-food', verbose_name='عکس'),
        ),
    ]
