# Generated by Django 6.0.4 on 2026-04-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_pishnahadroz_akss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='فرمت\u200cهای مجاز: jpg, png, gif, webp', upload_to='pic-food', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='sijal',
            name='image',
            field=models.ImageField(upload_to='pic-food', verbose_name='عکس'),
        ),
    ]
