# Generated by Django 6.0.4 on 2026-04-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='abot',
            field=models.TextField(default='default.jpg', verbose_name='محتویات غذا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='cover',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pic-food'),
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='default.jpg', max_length=30, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
