# Generated by Django 6.0.4 on 2026-04-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_abot_food_cover_food_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='qimat',
            field=models.CharField(max_length=30, null=True, verbose_name='قیمت'),
        ),
    ]
