# Generated by Django 6.0.4 on 2026-04-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_qimat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='qimat',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت (تومان)'),
        ),
    ]
